FROM golang:1.23 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o go-grpc-client grpc_client.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/go-grpc-client /go-grpc-client
EXPOSE 50051
CMD ["/go-grpc-client"]