apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: weather
  namespace: proyecto2
  labels:
    strimzi.io/cluster: my-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824